config/routes.rb
Bzr::Application.routes.draw do
  devise_for :users

  resources :articles do
    member do
      post :notify_friend
      post :email_owner
    end
  end

  root 'articles#index'

  get '/about' => "articles#about"
  get '/help' => "articles#help"

  get 'articles/:id' => "articles#show"

  post '/articles/search_articles' => 'articles#search', :as => "search_articles"

  get '/articles/search_autocomplete' => 'articles#search_autocomplete'

  

end

app/models/article.rb
class Article < ActiveRecord::Base

  #validates_presence_of :title, :body
  validates :title, :body, presence: true  # there is nothing wrong here. Tested!

  belongs_to :user

  simple_search :body

  before_save :clean_data, :remove_nbsp

  has_attached_file :image1, :styles => {
      :thumb => '50x50>',
      :square => '400x400#',
      :medium => '800x800>'
  }

  has_attached_file :image2, :styles => {
      :thumb => '50x50>',
      :square => '400x400#',
      :medium => '800x800>'
  }

  has_attached_file :image3, :styles => {
      :thumb => '50x50>',
      :square => '400x400#',
      :medium => '800x800>'
  }

  has_attached_file :image4, :styles => {
      :thumb => '50x50>',
      :square => '400x400#',
      :medium => '800x800>'
  }

  has_attached_file :image5, :styles => {
      :thumb => '50x50>',
      :square => '400x400#',
      :medium => '800x800>'
  }

  attr_accessor :delete_asset1, :delete_asset2, :delete_asset3, :delete_asset4, :delete_asset5

  before_validation do
    #puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ " + delete_asset1.nil?
    image1.clear if delete_asset1 == '1'
    image2.clear if delete_asset2 == '1'
    image3.clear if delete_asset3 == '1'
    image4.clear if delete_asset4 == '1'
    image5.clear if delete_asset5 == '1'
  end

  private
    def clean_data
      # trim whitespace from beginning and end of string attributes
      attribute_names().each do |name|
      if self.send(name.to_sym).respond_to?(:strip)
        self.send("#{name}=".to_sym, self.send(name).strip)
      end
      end
    end

    def remove_nbsp
      self.body = body.gsub(/[&nbsp;]*\<\/p\>$/i,"")
      self.body = body << "</p>"
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, :only=> [:edit, :update, :destroy, :notify_friend, :email_owner]
  before_action :set_params_before_update, only: :update
  before_filter :authenticate_user!, :except => [:index, :show, :notify_friend, :about, :help, :search, :search_autocomplete]
  #before_filter :set_current_user
  after_filter :mail, :only => :create
  before_action :search_param, :only => :search
  before_filter :set_about_and_help, :except => [:about, :help]

   def set_about_and_help
     @about = :about
     @help = :help
   end


  def search_autocomplete
       keyword = params[:q]
       h = Array.new
       if (keyword.length > 1)
         #puts "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% " + keyword
         @articles = Article.search(keyword)
         @articles.each do |article|
           @articles = h << ({:id => article.body, #this value goes into search_text parameter that is needed in search method in this class
                           :article => article.body.truncate(40, :separator => ' '),
                           :price => article.price})
         end
         @articles = @articles.sort_by { |k| k[:price] }

         respond_to do |format|
           format.js
           format.json { render json: @articles }  #autocomplete icin format.json { render json: @jobs} gerekiyor
         end
       end
  end

  def search
     if signed_in?
       @article = current_user.articles.build(params[:article])
     end
       sanitized_text = ActionController::Base.helpers.sanitize(search_param[:search_text], :tags=>[])
       @articles = Article.search(search_param[:search_text])
       #puts "########################################## " + sanitized_text
       @articles = @articles.paginate(page: params[:page])
       render 'articles/index'
  end

  def about
    @about = nil
  end

  def help
    @help = nil
  end

  def mail
    #Notice no observer is being used for article model
    Notifier.article_added(@article).deliver if (Rails.env.production? || Rails.env.development?)
  end

  def notify_friend

    @time_too_fast = ''
    time_later    # defined in application controller
    hidden_field  # defined in application controller

    if (params[:name].blank? || params[:email].blank?)
      flash[:alert] = "Missing Information"
      render 'show' and return
    end

    if (@hidden.blank? && @time_too_fast.blank?)
      Notifier.email_friend(@article, params[:name], params[:email]).deliver
      flash[:alert] = "Successfully notified friend"
      redirect_to @article
    else
      #params[:notice] = "Missing $$$$$$$$$$$$$$$$$$$$$ #{@hidden} #{@time_too_fast} $$$$$$$$$$$$ Information"
      render 'show'
    end
  end

  def email_owner

      @time_too_fast = ''
      time_later    # defined in application controller
      hidden_field  # defined in application controller

      if (params[:name].blank? || params[:email].blank?)
        flash[:alert] = "Missing Information"
        render 'show' and return
      end

      if (@hidden.blank? && @time_too_fast.blank?)
        Notifier.email_owner(@article, params[:name], params[:email], params[:message]).deliver
        flash[:alert] = "Successfully emailed owner"
        redirect_to @article
      else
        #params[:notice] = "Missing $$$$$$$$$$$$$$$$$$$$$ #{@hidden} #{@time_too_fast} $$$$$$$$$$$$ Information"
        render 'show'
      end
    end

  # GET /articles
  # GET /articles.json
  def index

    # to tell will_paginate how many items per page we want:
    @articles = Article.order("created_at DESC").paginate(page:params[:page], per_page: 30)
    session[:back_to] = nil  # :back_to defined in application_controller check_if_article method
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    if params[:id] == "search_autocomplete"
      search_autocomplete
    else
      @article = Article.find(params[:id])
      session[:time_now] = Time.now
    end
  end


  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit

  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user # current_user is set equal to so that in the
                                 # notifier.rb article_added method can use @article.user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
        #puts "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ #{@article.inspect}                             #{@article.user}"
        #puts "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% #{current_user}"
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy

    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :location, :body, :price, :image1,
                                      :image2, :image3, :image4, :image5, :delete_asset1, :delete_asset2,
                                      :delete_asset3, :delete_asset4, :delete_asset5)
    end

    def search_param
      params.permit(:utf8, :authenticity_token, :search_text)
    end

    def set_params_before_update
      @article.delete_asset1 = params[:delete_asset1]
      @article.delete_asset2 = params[:delete_asset2]
      @article.delete_asset3 = params[:delete_asset3]
      @article.delete_asset4 = params[:delete_asset4]
      @article.delete_asset5 = params[:delete_asset5]
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_email_owner.html.erb
<%= form_tag(email_owner_article_path(@article), :id => 'email_owner_form',:style => 'display:none') do %>
    <div class="field_email_owner">
      <%= label_tag :name, "Name" %>:<br />
      <%= text_field_tag :name, '', :class => "email_owner_name" %>
    </div>
    <div class="field_email_owner">
      <%= label_tag :email, "Email Address" %>:<br />
      <%= text_field_tag :email, '', :class => "email_owner_email" %>
    </div>
    <br />
    <div class="field_email_owner">
      <%= label_tag :message, "Message" %>:<br />
      <%= text_area_tag :message, '', :class => "email_owner_message" %>
    </div>
    <br />
    <%= hidden_field_tag(:hidden, '', :class => "hidden_field_tag") %>
    <div class="action_email_owner">
      <%= submit_tag "Send", :class => "email_owner_submit" %> &nbsp; OR &nbsp;
      <%= link_to "Cancel", '#', :onclick => "$('#email_owner_form').slideUp()" %>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article, :html => {:multipart => true}) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :country, "Country or State" %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :cell %><br>
    <%= f.text_field :cell %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <!-- tinymce height and width are set in application.css-->
    <%= f.text_area :body, :class => "tinymce" %>
  </div>
  <!--<div class="field">
    < f.label :published_at %><br>
    < f.datetime_select :published_at %>
  </div>-->

    <div class="field">
      <%= f.label :price %>
      &#36;
      <%= f.text_field :price %>
    </div>

    <br>

    <p>First Image will be shown on main listing page <br>
    To replace an image just select and upload another image</p>
    <div class="field">
      <%= f.label :image1 %>
      <%= f.file_field :image1 %>
      Current Uploaded Image1: <%= image_tag @article.image1.url, :size => "50x50" %>
    </div>

    <div class="field">
      <%= f.label :image2 %>
      <%= f.file_field :image2 %>
      Current Uploaded Image2: <%= image_tag @article.image2.url, :size => "50x50" %>
    </div>

    <div class="field">
      <%= f.label :image3 %>
      <%= f.file_field :image3 %>
      Current Uploaded Image3: <%= image_tag @article.image3.url, :size => "50x50" %>
    </div>

    <div class="field">
      <%= f.label :image4 %>
      <%= f.file_field :image4 %>
      Current Uploaded Image4: <%= image_tag @article.image4.url, :size => "50x50" %>
    </div>

    <div class="field">
      <%= f.label :image5 %>
      <%= f.file_field :image5 %>
      Current Uploaded Image5: <%= image_tag @article.image5.url, :size => "50x50" %>
    </div>

    <% if current_user && (@article.user_id == current_user.id || current_user.admin? ) %>
    <%= check_box_tag :delete_asset1 %> Delete Image1?<br>
    <%= check_box_tag :delete_asset2 %> Delete Image2?<br>
    <%= check_box_tag :delete_asset3 %> Delete Image3?<br>
    <%= check_box_tag :delete_asset4 %> Delete Image4?<br>
    <%= check_box_tag :delete_asset5 %> Delete Image5?<br>
    <% end %>

  <div class="actions field">
    <%= f.submit %>
  </div>
<% end %>

<br>

<%= tinymce %>

app/views/articles/_notify_friend.html.erb
<%= form_tag(notify_friend_article_path(@article), :id => 'notify_friend_form',:style => 'display:none') do %>
    <div class="field_notify_friend">
      <%= label_tag :name, "Name" %>:<br />
      <%= text_field_tag :name, '', :class => "notify_friend_name" %>
    </div>
    <div class="field_notify_friend">
      <%= label_tag :email, "Email Address" %>:<br />
      <%= text_field_tag :email, '', :class => "notify_friend_email" %>
    </div>
    <br />
    <%= hidden_field_tag(:hidden, '', :class => "hidden_field_tag") %>
    <div class="action_notify_friend">
      <%= submit_tag "Send", :class => "notify_friend_submit" %> &nbsp; OR &nbsp;
      <%= link_to "Cancel", '#', :onclick => "$('#notify_friend_form').slideUp()" %>
    </div>
<% end %>

app/views/articles/about.html.erb
<h1 class="text-center" style="margin-top: 200px">This is a Web Site that brings buyers and sellers together.</h1>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back to List', articles_path %>

app/views/articles/help.html.erb
<h1 class="text-center" style="margin-top: 200px;">Please email any questions or suggestions to
  <a href="mailto:coffeelatte2007@gmail.com?subject=FromItsOwner-Questions-Suggestions">Guney Bilen</a></h1>

app/views/articles/index.html.erb
<%= content_for :title, "Items Listing" %>

<div class= "center_index_page">
<span class="listing_items">Listing Items</span>
<% if current_user %>
<%= link_to 'New Item', new_article_path, class: "new_item_link" %>
<% else %>
<span class="sign_in_or_sign_up">
Sign in or Sign Up to create a new item.<%= link_to " Sign in/Sign up", new_user_session_path %>
</span>
<% end %>
<br /> <br />
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>City</th>
      <th>Body</th>
      <th>Price</th>
      <th class="created_at">Created at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% unless @articles.nil? %>
    <% @articles.each do |article| %>
      <tr class align="spacer">
        <% if article.image1.url.to_s == '/image1s/original/missing.png' %>
          <td>No Image</td>
        <% else %>
          <td><%= image_tag article.image1.url(:thumb) %></td>
        <% end %>
        <td class="title"><%= article.title %></td>
        <td><%= article.city %></td>
        <% body = article.body.slice!(0..150) %>
        <% dotter body %>
        <!-- below sanitize allows no tags and no attributes through in the index page. -->
        <td><%= sanitize body, :tags => %w(), :attributes => %w() %></td>
        <td><%= number_to_currency article.price %></td>
        <td class="created_at"><%= time_ago_in_words(article.created_at) %> ago </td>
        <td><%= link_to 'Show', article %></td>
        <% if current_user && (article.user_id == current_user.id || current_user.admin? ) %>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<br/><br/><br/>
  <% unless @articles.nil? %>
    <%= will_paginate @articles, class: "digg_pagination"  %>
  <% end %>

</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back to List', articles_path %>

app/views/articles/show.html.erb
<div class="show-page">
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>Country or State:</strong>
  <%= @article.country %>
</p>
<p>
  <strong>City:</strong>
  <%= @article.city %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @article.phone %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @article.cell %>
</p>

<p>
  <strong>Body:</strong>
  <%= sanitize @article.body.strip %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @article.price %>
</p>

<% if current_user && @article.user != current_user %>
  <%= link_to "Email To the Owner", '#',
            :id => "show_link_to_email_owner" %>
  <%= render 'articles/email_owner' %>
<% else %>
     Sign in or Sign Up to email owner.<%= link_to " Sign in/Sign up", new_user_session_path %>
<% end %>

<br><br>

<%= link_to "Email This Item to a Friend", '#',
        :id => "show_link_to_email_friend" %>
<br /> <br />

<%= render 'articles/notify_friend' %>
<br />

  <% if @article.image1.url.to_s == '/image1s/original/missing.png' %>
    No reecorded image-1.
  <% else %>
    <%= image_tag @article.image1.url(:medium) %>
  <% end %>

<br>
  <% if @article.image2.url.to_s == '/image2s/original/missing.png' %>
    No reecorded image-2. <br>
  <% else %>
    <%= image_tag @article.image2.url(:square) %>
  <% end %>

  <% if @article.image3.url.to_s == '/image3s/original/missing.png' %>
    No reecorded image-3.
  <% else %>
    <%= image_tag @article.image3.url(:square) %>
  <% end %>

<br>

    <% if @article.image4.url.to_s == '/image4s/original/missing.png' %>
      No reecorded image-4. <br>
    <% else %>
      <%= image_tag @article.image4.url(:square) %>
    <% end %>

    <% if @article.image5.url.to_s == '/image5s/original/missing.png' %>
      No reecorded image-5. <br>
    <% else %>
      <%= image_tag @article.image5.url(:square) %>
    <% end %>


<br><br>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back to List', articles_path %>
</div>