config/routes.rb
Bzr::Application.routes.draw do
  devise_for :users

  resources :articles do
    member do
      post :notify_friend
      post :email_owner
    end
  end

  root 'articles#index'

  get '/about' => "articles#about"
  get '/help' => "articles#help"

  get 'articles/:id' => "articles#show"

  post '/articles/search_articles' => 'articles#search', :as => "search_articles"

  get '/articles/search_autocomplete' => 'articles#search_autocomplete'

  

end

app/views/shared/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "FromItsOwner", '#', :class=>"navbar-brand", :id => "brand" %>
    </div>
    <div class="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", '#', :id => "home" %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if current_user %>
            ,    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hello, <%= current_user.name.capitalize %> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
                      <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                    </ul>
                  </li>
        <% else %>
          <li><%= link_to "Sign in/Sign up", new_user_session_path %></li>
        <% end %>

      </ul>

      <% if ((!@about.nil?) || (!@help.nil?)) %>


            <%= form_tag  search_articles_path, class: "form-search",
                             id: "search_articles_form" do %>

            <%= text_field_tag :search_text, '',
                            { placeholder: "Search Items...",
                              class: "input-medium search-query",
                              id: "search_articles_form_text_field" } %>

            <button type="submit" name="" class="btn btn-primary"
                  id="search_articles_form_submit_button">
              <i class="icon-search icon-white"></i> Search
            </button>

            <% end %>
          <% end %>
        </div>
     </div>
 </div>